export const mybookingData={
    "success": true,
    "message": "Bookings fetched successfully",
    "data":{
        "upcoming": [
            {
                "id": 1,
                "hotelId": 1,
                "userId": 1,
                "roomIds": 1,
                "startDate": "2025-03-10T00:00:00.000Z",
                "endDate": "2025-03-15T00:00:00.000Z",
                "checkInTime": "14:00:00",
                "checkOutTime": "11:00:00",
                "adultsCount": 2,
                "childrenCount": 1,
                "infantsCount": 0,
                "petsCount": 1,
                "specialCareCount": 0,
                "bookingStatus": "PENDING",
                "cancellationReason": null,
                "paymentStatus": "PENDING",
                "paymentMode": null,
                "currency": "USD",
                "calculatedPrice": "0.00",
                "basePrice": "0.00",
                "taxesAndFees": "0.00",
                "refundAmount": "0.00",
                "partiallyPaidAmount": "0.00",
                "promoCodeUsed": null,
                "transactionId": null,
                "createdAt": "2025-02-28T08:11:31.000Z",
                "updatedAt": "2025-02-28T08:11:31.000Z",
                "hotel": {
                    "name": "The Grand Palace",
                    "address": "123 Royal Street",
                    "contactNumber": "+1 212-555-1234",
                    "city": "New York",
                    "state": "New York",
                    "country": "USA",
                    "latitude": "40.71280000",
                    "longitude": "-74.00600000"
                }
            },
            {
                "id": 2,
                "hotelId": 1,
                "userId": 1,
                "roomIds": 1,
                "startDate": "2025-02-12T00:00:00.000Z",
                "endDate": "2025-01-16T00:00:00.000Z",
                "checkInTime": "14:00:00",
                "checkOutTime": "11:00:00",
                "adultsCount": 3,
                "childrenCount": 1,
                "infantsCount": 6,
                "petsCount": 3,
                "specialCareCount": 2,
                "bookingStatus": "PENDING",
                "cancellationReason": null,
                "paymentStatus": "PENDING",
                "paymentMode": null,
                "currency": "USD",
                "calculatedPrice": "0.00",
                "basePrice": "0.00",
                "taxesAndFees": "0.00",
                "refundAmount": "0.00",
                "partiallyPaidAmount": "0.00",
                "promoCodeUsed": null,
                "transactionId": null,
                "createdAt": "2025-02-28T13:07:41.000Z",
                "updatedAt": "2025-02-28T13:07:41.000Z",
                "hotel": {
                    "name": "The Grand Palace",
                    "address": "123 Royal Street",
                    "contactNumber": "+1 212-555-1234",
                    "city": "New York",
                    "state": "New York",
                    "country": "USA",
                    "latitude": "40.71280000",
                    "longitude": "-74.00600000"
                }
            }
        ],
        "active": [
            {
                "id": 6,
                "hotelId": 1,
                "userId": 1,
                "roomIds": 1,
                "startDate": "2025-02-12T00:00:00.000Z",
                "endDate": "2025-01-16T00:00:00.000Z",
                "checkInTime": "14:00:00",
                "checkOutTime": "11:00:00",
                "adultsCount": 3,
                "childrenCount": 1,
                "infantsCount": 6,
                "petsCount": 3,
                "specialCareCount": 2,
                "bookingStatus": "PENDING",
                "cancellationReason": null,
                "paymentStatus": "PENDING",
                "paymentMode": null,
                "currency": "USD",
                "calculatedPrice": "0.00",
                "basePrice": "0.00",
                "taxesAndFees": "0.00",
                "refundAmount": "0.00",
                "partiallyPaidAmount": "0.00",
                "promoCodeUsed": null,
                "transactionId": null,
                "createdAt": "2025-02-28T13:22:19.000Z",
                "updatedAt": "2025-02-28T13:22:19.000Z",
                "hotel": {
                    "name": "The Grand Palace",
                    "address": "123 Royal Street",
                    "contactNumber": "+1 212-555-1234",
                    "city": "New York",
                    "state": "New York",
                    "country": "USA",
                    "latitude": "40.71280000",
                    "longitude": "-74.00600000"
                }
            }
        ],
        "checkedOut": [
            {
                "id": 7,
                "hotelId": 1,
                "userId": 1,
                "roomIds": 1,
                "startDate": "2025-02-12T00:00:00.000Z",
                "endDate": "2025-01-16T00:00:00.000Z",
                "checkInTime": "14:00:00",
                "checkOutTime": "11:00:00",
                "adultsCount": 3,
                "childrenCount": 1,
                "infantsCount": 6,
                "petsCount": 3,
                "specialCareCount": 2,
                "bookingStatus": "PENDING",
                "cancellationReason": null,
                "paymentStatus": "PENDING",
                "paymentMode": null,
                "currency": "USD",
                "calculatedPrice": "0.00",
                "basePrice": "0.00",
                "taxesAndFees": "0.00",
                "refundAmount": "0.00",
                "partiallyPaidAmount": "0.00",
                "promoCodeUsed": null,
                "transactionId": null,
                "createdAt": "2025-02-28T13:26:43.000Z",
                "updatedAt": "2025-02-28T13:26:43.000Z",
                "hotel": {
                    "name": "The Grand Palace",
                    "address": "123 Royal Street",
                    "contactNumber": "+1 212-555-1234",
                    "city": "New York",
                    "state": "New York",
                    "country": "USA",
                    "latitude": "40.71280000",
                    "longitude": "-74.00600000"
                }
            }
        ],
        "cancelled": []
    },
    "code": 200
}